services:
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - web
    volumes:
      - pdf-data:/app/backend/pdf/ 
    ports:
      - 8000
  
  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - web
    ports:
      - 3000:3000

volumes:
  pdf-data:

networks:
  web: